version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-01
    steps:
      - checkout
    
      - run:
          name: Install dependencies
          command: npm install
          
      - run:
          name: Cypress install
          command: npx cypress install
          
      - run:
          name: Run tests
          command: npx cypress run
