version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --spec "cypress/e2e/product.feature" --parallel --record --group smoke-tests'
          parallelism: 3
